services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: backend-app:latest
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_BASE_URL=https://api.shoppi.lat
        - NEXT_PUBLIC_DOCKER_ENV=true
        - NEXT_PUBLIC_DOMAIN=shoppi
        - NEXT_PUBLIC_DOMAIN_NAME=https://shoppi.lat
    ports:
      - "3000:3000"

  proxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      environment:
      - FRONTEND_DOMAIN=shoppi.lat
      - BACKEND_DOMAIN=api.shoppi.lat
    ports:
      - "443:443"