name: Backend CD

on:
  push:
    branches: [main]
    paths: ['backend/**', 'shared/**']

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          target: runner 
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/shoppi-backend:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/shoppi-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Update ECS Service
        run: aws ecs update-service --cluster shoppi-cluster --service shoppi-app --force-new-deployment